## List Comprehension

반복 가능한 자료형에서 리스트를 만들어 내는 것  

In [1]:
x = 'ABC'

In [2]:
dummy = [ord(x) for x in x]  # list comprehension

In [3]:
x

'ABC'

In [4]:
dummy

[65, 66, 67]

map()과 filter()를 사용하는 작업은 list comprehension으로 구현 가능  

In [5]:
symbols = "$#%*^&!@~"

In [6]:
listcomp = [ord(s) for s in symbols if ord(s) < 127]

In [7]:
listcomp

[36, 35, 37, 42, 94, 38, 33, 64, 126]

In [8]:
beyond_ascii = list(filter(lambda c: c < 127, map(ord, symbols)))

In [9]:
beyond_ascii

[36, 35, 37, 42, 94, 38, 33, 64, 126]

데카르트 곱 : 두 개 이상의 리스트에 있는 모든 항목을 이용해 만든 튜플로 구성된 리스트  

In [10]:
colors = ['black', 'white']

In [11]:
sizes = ['S', 'M', 'L']

In [12]:
tshirts = [(color, size) for color in colors for size in sizes]

In [13]:
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [14]:
for color in colors:
    for size in sizes:
        print((color, size))

('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [15]:
tshirts = [(color, size) for size in sizes
                         for color in colors]

In [16]:
tshirts

[('black', 'S'),
 ('white', 'S'),
 ('black', 'M'),
 ('white', 'M'),
 ('black', 'L'),
 ('white', 'L')]

## Generator Expression

반복자 프로토콜을 이용해 항목을 하나씩 생성 (메모리를 더 적게 사용함)  

In [17]:
symbols = "$#%*^&!@~"

In [18]:
# 제너레이터 표현식이 함수의 매개변수로 하나라면 괄호 없어도 됨
tuple( ord(symbol) for symbol in symbols )

(36, 35, 37, 42, 94, 38, 33, 64, 126)

In [19]:
import array

In [20]:
# 인수가 두 개이므로 반드시 괄호를 넣음
array.array('I', (ord(symbol) for symbol in symbols))

array('I', [36, 35, 37, 42, 94, 38, 33, 64, 126])

In [21]:
colors = ['red', 'blue']

In [22]:
sizes = ['S', 'M', 'L']

제너레이터 표현식에서의 데카르트 곱  
제너레이터 표현식은 한 번에 하나의 항목을 생성함  
리스트로 반환하지 않음  

In [23]:
for tshirt in ("%s %s" % (c, s) for c in colors for s in sizes):
    print(tshirt)

red S
red M
red L
blue S
blue M
blue L


## Tuple

### Tuple : Record

튜플은 레코드를 담고 있다.  
튜플의 각 항목은 레코드의 필드 하나를 의미하고 항목의 위치가 의미를 결정한다.  

In [24]:
lax_coordinates = (33.9425, -118.408056)

In [25]:
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)

In [26]:
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]

In [27]:
for passport in sorted(traveler_ids):
    print('%s/%s' % passport)  # passport의 각 항목을 할당

BRA/CE342567
ESP/XDA205856
USA/31195855


In [28]:
# for loop -> tuple unpacking
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


#### Tuple Unpacking, Iterable Unpacking

반복 가능한 객체라면 적용 가능  

병렬 할당 (parallel assignment)

In [29]:
lax_coordinates = (33.9425, -118.408056)

In [30]:
latitude, longitude = lax_coordinates  # tuple unpacking

In [31]:
latitude

33.9425

In [32]:
longitude

-118.408056

튜플 언패킹을 이용한 변수의 값의 교환

In [33]:
a, b = 10, 5

In [34]:
a, b

(10, 5)

In [35]:
a, b = b, a

In [36]:
a, b

(5, 10)

함수 호출 시 인수 앞에 \*을 붙여 튜플을 언패킹

In [37]:
divmod(20, 8)

(2, 4)

In [38]:
t = (20, 8)

In [39]:
divmod(*t)

(2, 4)

In [40]:
quotient, remainder = divmod(*t)

In [41]:
quotient

2

In [42]:
remainder

4

In [43]:
# 더미 변수를 이용하여 관심 없는 부분은 언패킹 시 무시 가능
import os
_, filename = os.path.split('/Users/nahyeonan/.ssh/idrsa.pub')

In [44]:
filename

'idrsa.pub'

초과 항목을 가져오기 : * 을 이용하여

In [45]:
a, b, *rest = range(5)

In [46]:
a, b, rest

(0, 1, [2, 3, 4])

In [47]:
a, b, *rest = range(3)

In [48]:
a, b, rest

(0, 1, [2])

In [49]:
a, b, *rest = range(2)

In [50]:
a, b, rest

(0, 1, [])

병렬 할당에서 \*는 단 하나의 변수에만 적용할 수 있다.  
그러나 어떤 변수라도 위치에 상관 없이 적용할 수 있다.  

In [51]:
a, *body, c, d = range(5)

In [52]:
a, body, c, d

(0, [1, 2], 3, 4)

In [53]:
*head, b, c, d = range(5)

In [54]:
head, b, c, d

([0, 1], 2, 3, 4)

#### 내포된 튜플 언패킹  

튜플 안에 다른 튜플을 내포한 경우도 언패킹 가능하다.  

In [55]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]

In [56]:
print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'
# 마지막 좌표를 튜플(lat, long)에 할당하여 언패킹
for name, cc, pop, (latitude, longitude) in metro_areas:
    if longitude <= 0:
        print(fmt.format(name, latitude, longitude))

                |   lat.    |   long.  
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


#### 명명된 튜플 namedtuple

collections.namedtuple() 함수는 필드명과 클래스명을 추가한 튜플의 서브클래스를 생성하는 팩토리 함수로 디버깅 시 유용하다.  

In [57]:
from collections import namedtuple

In [58]:
# namedtuple( 클래스명, 필드명 리스트 )
# 필드명 리스트 : 반복형 문자열 or 공백으로 구분되는 하나의 문자열
City = namedtuple('City', 'name country population coordinates')

In [59]:
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))

In [60]:
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))

In [61]:
tokyo.population

36.933

In [62]:
tokyo.coordinates

(35.689722, 139.691667)

In [63]:
tokyo[1]

'JP'

명명된 튜플은 튜플에서 상속받은 속성과 추가적인 속성을 더 가지고 있다.  

In [64]:
City._fields  # 클래스의 필드명을 담는 튜플

('name', 'country', 'population', 'coordinates')

In [65]:
LatLong = namedtuple('LatLong', 'lat long')

In [66]:
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889))

In [67]:
# 반복형 객체에서 명명된 튜플을 만듦
# City(*delhi_data)와 동일
delhi = City._make(delhi_data)  

In [68]:
delhi._asdict()  # namedtuple 객체를 OrderedDict 객체로 반환함

OrderedDict([('name', 'Delhi NCR'),
             ('country', 'IN'),
             ('population', 21.935),
             ('coordinates', LatLong(lat=28.613889, long=77.208889))])

In [69]:
for key, val in delhi._asdict().items():
    print(key + ':', val)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613889, long=77.208889)


### 튜플 : 불변 리스트

리스트와 얼마나 비슷한지를 알면 이해할 수 있다.  
튜플은 항목 추가, 삭제, \_\_reversed__() 등의 메서드를 제외하고 리스트가 제공하는 메서드를 모두 지원한다.  

## Slicing

파이썬의 모든 시퀀스형은 슬라이싱 연산을 지원한다.  

In [70]:
l = [10, 20, 30, 40, 50, 60]

In [71]:
l[:2]

[10, 20]

In [72]:
l[2:]

[30, 40, 50, 60]

In [73]:
l[:3]

[10, 20, 30]

In [74]:
l[3:]

[40, 50, 60]

s\[a:b:c\] 는 c 보폭씩 항목을 건너뛰는 슬라이싱이다.  
보폭 c가 음수라면 반대 방향으로 올라간다.  

In [75]:
s = 'bicycle'

In [76]:
s[::3]

'bye'

In [77]:
s[::-1]

'elcycib'

In [78]:
s[::-2]

'eccb'

s\[a:b:c\] 의 표기법은 인덱스 연산을 수행하는 \[\]안에서만 사용 가능하다.  
slice(a, b, c) 객체를 생성한다. 

In [79]:
invoice = """
0.....6.................................40...........52...55.......
1909  Pimoraoni PiBrella                      $17.50      3  $52.50
1489  6mm tactile Switch x20                   $4.95      2   $9.90
1510  Panavise Jr. - PV-201                   $28.00      1  $28.00
1601  PiTFT Mini Kit 320x240                  $34.95      1  $34.95
"""

In [80]:
SKU = slice(0, 6)

In [81]:
DESCRIPTION = slice(6, 40)

In [82]:
UNIT_PRICE = slice(40, 52)

In [83]:
QUANTITY = slice(52, 55)

In [84]:
ITEM_TOTAL = slice(55, None)

In [85]:
line_items = invoice.split('\n')[2:]

In [86]:
for item in line_items:
    # 인덱스에 슬라이스 객체를 전달하여 슬라이싱 가능
    print(item[UNIT_PRICE], item[DESCRIPTION])

      $17.50 Pimoraoni PiBrella                
       $4.95 6mm tactile Switch x20            
      $28.00 Panavise Jr. - PV-201             
      $34.95 PiTFT Mini Kit 320x240            
 


In [87]:
for item in line_items:
    print(item)

1909  Pimoraoni PiBrella                      $17.50      3  $52.50
1489  6mm tactile Switch x20                   $4.95      2   $9.90
1510  Panavise Jr. - PV-201                   $28.00      1  $28.00
1601  PiTFT Mini Kit 320x240                  $34.95      1  $34.95



슬라이스에 할당하기

In [88]:
l = list(range(10))

In [89]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [90]:
l[2:5] = [20, 30]

In [91]:
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [92]:
del l[5:7]

In [93]:
l

[0, 1, 20, 30, 5, 8, 9]

In [94]:
l[3::2] = [11, 22]

In [95]:
l

[0, 1, 20, 11, 5, 22, 9]

할당문의 대상이 슬라이스일 때, 하나의 값만 할당하더라도 오른쪽에는 반복 가능한 객체가 할당되어야 한다.  

In [96]:
l[2:5] = 100

TypeError: can only assign an iterable

In [97]:
l[2:5] = [100]

In [98]:
l

[0, 1, 100, 22, 9]

## 시퀀스의 덧셈, 곱셈 등 연결연산과 동작 방식  

덧셈, 곱셈 연산자는 항상 새로운 객체를 만든다. 피연산자를 변경하지 않는다.   

In [99]:
l = [1, 2, 3]

In [100]:
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [101]:
5 * 'abc'

'abcabcabcabcabc'

caution : a * n을 사용할 때 주의해야 한다.

In [102]:
my_list = [['a', 'b']] * 3

In [103]:
# 내부 리스트에 대한 참조를 3개 가지는 리스트가 생성됨  
my_list

[['a', 'b'], ['a', 'b'], ['a', 'b']]

내포된 리스트를 가진 리스트를 초기화하는 방법에 대해 알아본다.

In [104]:
board = [['_'] * 3 for i in range(3)]

In [105]:
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [106]:
board[1][2] = 'X'

In [107]:
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [108]:
# 최상위 리스트가 동일한 내부 리스트의 참조를 3개 가진다.
weird = [['_'] * 3] * 3

In [109]:
weird

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [110]:
weird[1][2] = 'O'

In [111]:
weird

[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]

In [112]:
# weird 를 만드는 코드는 다음과 같이 동작한다.
row = ['_'] * 3
weird_board = []
for i in range(3):
    weird_board.append(row)  # 동일한 행이 3번 추가된다.

In [113]:
# board 를 만다는 코드는 다음과 같이 동작한다.
true_board = []
for i in range(3):
    row = ['_'] * 3  # 반복마다 새로운 row 객체를 만든다. (당연히 참조값이 다르다)
    true_board.append(row)

In [114]:
true_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [115]:
true_board[2][0] = 'X'

In [116]:
true_board

[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

## 시퀀스의 복합 할당

In [117]:
# 가변 시퀀스
l = [1, 2, 3]

In [118]:
id(l)

140264315586592

In [119]:
l *= 2

In [120]:
l

[1, 2, 3, 1, 2, 3]

In [121]:
id(l)

140264315586592

In [122]:
# 불변 시퀀스
t = (1, 2, 3)

In [123]:
id(t)

140264312684864

In [124]:
t *= 2

In [125]:
id(t)  # id가 변함 = 새로운 튜플 객체를 생성하여 t에 할당함 

140264314613840

In [126]:
t = (1, 2, [30, 40])

In [127]:
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [128]:
t

(1, 2, [30, 40, 50, 60])

In [129]:
import dis

In [130]:
dis.dis('s[a] += b')

  1           0 LOAD_NAME                0 (s)
              2 LOAD_NAME                1 (a)
              4 DUP_TOP_TWO
              6 BINARY_SUBSCR
              8 LOAD_NAME                2 (b)
             10 INPLACE_ADD
             12 ROT_THREE
             14 STORE_SUBSCR
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE


위의 퀴즈에서 얻을 수 있는 교훈  
- 가변 항목을 튜플에 넣지 마라  
- 복합 할당은 원자적인 연산이 아니다.  
- 파이썬 바이트코드를 살펴보는 것은 어렵지 않으며, 내부에서 어떤 일이 발생하는지 살펴보는 데에 도움이 된다.  

## list.sort() 와 sorted()  
list.sort() : 사본을 만들지 않고 리스트 내부를 변경하여 정렬한다.  
타깃 객체를 변경하고 새로운 리스트를 생성하지 않았음을 알려주기 위해 None을 리턴한다.  

*파이썬의 중요한 관례 : 객체를 직접 변경하는 메서드, 함수는 객체가 변경되었고 새로운 객체가 생성되지 않았음을 알리기 위해 반드시 None을 호출해야 한다.*  

sorted() : 새로운 리스트를 생성해서 반환한다. 불변 시퀀스, 제너레이터를 포함한 반복 가능한 모든 객체를 인수로 받을 수 있다.  
항상 새로 생성한 리스트를 반환한다.  

list.sort() 와 sorted() 모두 2개의 키워드를 인수로 받는다.  
- reverse : 참이면 내림차순으로 반환한다. default = False
- key : 각 항목에 적용할 키 생성 함수를 인수로 받는다. 적용된 함수로 키를 생성하여 정렬한다.  

In [131]:
fruits = ['grape', 'raspberry', 'apple', 'banana']

In [132]:
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [133]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [134]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [135]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [136]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [137]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [138]:
fruits.sort()  # None을 반환한다. 콘솔은 None이 반환되면 값을 보여주지 않는다.

In [139]:
fruits

['apple', 'banana', 'grape', 'raspberry']

## 정렬된 시퀀스를 bisect로 관리

bisect 모듈은 bisect() 와 insort() 함수를 제공한다.  
bisect() : 이진 탐색 알고리즘을 이용한 시퀀스 검색  
insort() : 정렬된 시퀀스 안에 항목을 삽입  

bisect() 의 선택 인수로 lo, hi가 있다.  
lo의 기본값은 0, hi의 기본값은 len() 이다.  

In [140]:
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}     {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * '  |'
        print(ROW_FMT.format(needle, position, offset))
        
if __name__ == '__main__':
    if sys.argv[-1] == 'left':
        # (삽입하려는 값이 이미 존재할 때) 수직 막대를 기준으로 왼쪽에 삽입하는 함수
        bisect_fn = bisect.bisect_left
    else:
        # bisect_right : 수직 막대를 기준으로 오른쪽에 삽입
        bisect_fn = bisect.bisect
        
    print('DEMO:', bisect_fn.__name__)
    print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)

DEMO: bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14       |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14       |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13       |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11       |  |  |  |  |  |  |  |  |  |  |23
22 @  9       |  |  |  |  |  |  |  |  |22
10 @  5       |  |  |  |  |10
 8 @  5       |  |  |  |  |8 
 5 @  3       |  |  |5 
 2 @  1       |2 
 1 @  1       |1 
 0 @  0     0 


In [141]:
def grade(score, breakpoints=[60, 70, 80, 90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

In [142]:
[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

insort(seq, item) : seq를 오름차순으로 유지한 채로 item을 seq에 삽입    
bisect() 와 마찬가지로 lo, hi 로 범위를 조정할 수 있다.  
insort_left() 함수도 있다.  

In [143]:
import bisect
import random

SIZE = 7

random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d -> ' % new_item, my_list)

10 ->  [10]
 0 ->  [0, 10]
 6 ->  [0, 6, 10]
 8 ->  [0, 6, 8, 10]
 7 ->  [0, 6, 7, 8, 10]
 2 ->  [0, 2, 6, 7, 8, 10]
10 ->  [0, 2, 6, 7, 8, 10, 10]


## 리스트가 답이 아닐 때

실수를 천만 개 저장할 때는 리스트보다 배열이 더 효율적이다.  
배열은 float 객체 대신 C언어의 배열처럼 바이트 값만 저장한다.  

리스트의 양쪽 끝에서 항목을 추가하거나 삭제할 때는 deque가 더 빠르다.  

array.array 는 숫자만 존재할 때 훨씬 효율적이다.  
pop(), insert(), extend() 등을 포함해 가변 시퀀스의 모든 연산이 가능하다.  
빠르게 파일에 저장하고 읽을 수 있는 frombytes(), tofile() 메서드가 추가 제공된다.  

파이썬의 배열은 C 배열만큼 가볍다.  
배열을 생성할 때 배열에 저장할 항목의 타입을 결정하는 문자인 typecode를 지정해야 한다.  
지정한 타입에 맞지 않는 숫자는 저장할 수 없다.  

무작위의 실수를 천만개 저장하는 배열을 생성/저장/로딩해보자.

In [144]:
from array import array

In [145]:
from random import random

In [146]:
floats = array('d', (random() for i in range(10**7)))

In [147]:
floats[-1]

0.5963321947530882

In [148]:
with open('floats.bin', 'wb') as fp:
    floats.tofile(fp)

In [149]:
floats2 = array('d')

In [150]:
with open('floats.bin', 'rb') as fp:
    floats2.fromfile(fp, 10**7)

In [151]:
floats2[-1]

0.5963321947530882

In [152]:
floats2 == floats

True

객체를 직렬화하는 pickle 모듈도 숫자 데이터를 빠르고 효율적으로 저장할 수 있다.  
pickle.dump() 메서드는 실수 배열을 array.tofile() 메서드만큼 빠르게 저장한다.  
\+ 복소수, 내포된 컬렉션, 사용자 정의 객체 등 모든 내장 자료형을 처리할 수 있다.  

array 형은 list.sort() 처럼 배열을 직접 변경하는 메서드는 없다.  
배열을 정렬하려면 sorted() 함수를 호출하고 새롭게 array를 만들어야 한다.  

In [153]:
a = floats

In [154]:
a = array(a.typecode, sorted(a))

In [155]:
a[:5], a[-5:]

(array('d', [1.3204618898310372e-07, 1.438214560778306e-07, 2.6395568086812204e-07, 3.0406143480821157e-07, 3.2941991068291543e-07]),
 array('d', [0.9999993906619695, 0.9999994343939265, 0.9999996435888285, 0.999999798751504, 0.9999998826771785]))

#### 메모리 뷰 

메모리 뷰 내장 클래스 : 공유 메모리 시퀀스형, bytes를 복사하지 않고 배열의 슬라이스를 다룰 수 있다.  

메모리 뷰는 언제 사용해야 하는가?  
- 메모리 뷰는 numpy 배열 구조체를 일반화한 것이다.  
- PIL 이미지, SQLlite DB, numpy 배열 등 데이터 구조체를 복사하지 않고 메모리를 공유하게 하는 기법이다.  
- 데이터셋이 커질 때 중요한 기법이다. 

memoryview.cast() 메서드는 바이트를 이동시키지 않고,  
C언어의 형변환 연산자처럼 여러 바이트로 된 데이터를 읽거나 쓰는 방식을 바꿀 수 있게 해준다.  
memoryview.cast()는 또 다른 memoryview 객체를 반환하며 언제나 동일한 메모리를 공유한다.  

16비트 정수 배열에서 바이트 하나를 변경해보자  

In [156]:
import array

In [157]:
# h : 짧은 정수 타입
numbers = array.array('h', [-2, -1, 0, 1, 2])

In [158]:
memv = memoryview(numbers)

In [159]:
len(memv)

5

In [160]:
memv[0]

-2

In [161]:
# memv 요소를 unsigned char ('B') 로 형변환한 memv_oct를 생성한다. 
memv_oct = memv.cast('B')

In [162]:
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [163]:
# memv_oct[5]는 현재 0임 -> 4로 변환 -> 2byte unsigned int의 최상위 바이트에서 4 는 1024를 의미한다
# numbers[2]는 memv_oct[4] : 00000000, memv_oct[5] : 00100000 로 변함
memv_oct[5] = 4

In [164]:
numbers

array('h', [-2, -1, 1024, 1, 2])

In [165]:
memv_oct.tolist()

[254, 255, 255, 255, 0, 4, 1, 0, 2, 0]

#### numpy와 scipy

너무 훌륭한 라이브러리다.  
두 라이브러리가 제공하는 고급 배열, 행렬 연산 덕분에 파이썬이 과학 계산에서 널리 사용되게 되었다.  

scipy는 numpy 기반으로 작성되었다.  
선형대수, 수치해석, 통계학 등의 여러 과학 계산 알고리즘을 제공한다.  

In [166]:
import numpy

In [167]:
a = numpy.arange(12)

In [168]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [169]:
type(a)

numpy.ndarray

In [170]:
a.shape

(12,)

In [171]:
a.shape = 3, 4

In [172]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [173]:
a[2]

array([ 8,  9, 10, 11])

In [174]:
a[2, 1]

9

In [175]:
a[:, 1]

array([1, 5, 9])

In [176]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

numpy.ndarray 의 모든 요소를 저장, 로딩, 처리하는 고급 연산도 지원한다.  

In [177]:
with open('floats-10M.txt', 'w', encoding='utf8') as fp:
    fp.write("\n".join(map(str, floats)))

In [178]:
floats = numpy.loadtxt('floats-10M.txt')

In [179]:
floats[-3:]

array([0.53879831, 0.55090456, 0.59633219])

In [180]:
floats *= .5

In [181]:
floats[-3:]

array([0.26939915, 0.27545228, 0.2981661 ])

In [182]:
from time import perf_counter as pc

In [183]:
# 모든 요소를 3으로 나눈다.
# 실수형 천만개를 처리하는 데에 걸리는 시간을 보자. 
t0 = pc(); floats /= 3; pc() - t0

0.012142382999996926

In [184]:
# 배열을 .npy 이진 파일에 저장한다.
numpy.save('floats-10M', floats)

In [185]:
floats2 = numpy.load('floats-10M.npy', 'r+')

In [186]:
floats2 *= 6

In [187]:
floats2[-3:]

memmap([0.53879831, 0.55090456, 0.59633219])

#### deque 와 기타 큐

리스트를 스택이나 큐로 사용할 수 있다.  
그러나 리스트의 0번 인덱스에 삽입, 삭제 연산은 전체 리스트를 이동시키므로 처리 부담이 크다.  

collections.deque 는 큐의 양쪽에서 빠르게 삽입, 삭제할 수 있도록 설계된 스레드 안전한(thread-safe) 양방향 큐이다.  
최대 길이를 설정해서 제한된 항목만 유지하도록 만들 수도 있다.  
deque가 꽉 찬 이후 새로운 항목을 추가하면 반대 방향 항목을 버린다.  

In [188]:
from collections import deque

In [189]:
dq = deque(range(10), maxlen=10)

In [190]:
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [191]:
dq.rotate(3)

In [192]:
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [193]:
dq.rotate(-4)

In [194]:
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [195]:
dq.appendleft(-1)

In [196]:
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
dq.extend([11, 22, 33])

In [198]:
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [199]:
dq.extendleft([10, 20, 30, 40])

In [200]:
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])